apiVersion: batch/v1
kind: CronJob
metadata:
  name: vulcan-anomaly-detector-staging
  labels:
    app: vulcan-anomaly-detector-staging
spec:
  schedule: "0 0 * * *"
  suspend: true
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          name: vulcan-anomaly-detector-staging
          labels:
            app: vulcan-anomaly-detector-staging
        spec:
          dnsPolicy: None
          dnsConfig:
            nameservers:
              - 10.2.0.4
              - 10.2.0.16
          containers:
          - name: vulcan-anomaly-detector-container
            image: connecterra.azurecr.io/vulcan-anomaly-detector-staging:latest
            command: [ "python" ]
            args: [ "evaluate.py" ]
            envFrom:
              - secretRef:
                  name: vulcananomalyenvsecrets
          imagePullSecrets:
          - name: docker-azure-auth
          restartPolicy: Never